### PR TITLE
Added option "noDivWrapper" to suppress <div> wrappers

### PR DESCRIPTION
**Pull request by mklement0**
Note that this implicitly fixes the nested-div-wrappers bug with array input data (issue #101), but only if you turn option 'noDivWrapper' on.

### CODE REVIEW

**Comment by mklement0** [comment]
I'm not 100% confident in this change, but it seems to work well for my purposes. I hope it at least points you in the right direction.

**Comment by bartoszzajac** [comment]
I'm new on github :) How can I use this modification?

**Comment by itimryan** [comment]
Thanks for your nice job @mklement0 
It works good!

**Comment by codepb** [comment]
I'll check when I get the chance and merge. I'm also considering whether this is just an underlying bug that should be fixed.

**Comment by mklement0** [comment]
@codepb Thanks. If you're not concerned about backward compatibility, I'd say it's probably worth treating it as a bug (if you're using semantic versioning, you could just bump the major version number).

**Comment by gmazza** [comment]
Thanks for the PR @mklement0, I just started experimenting with jquery-template yesterday, and immediately ran into this problem.  I was hoping to use this tool to [generate multiple table rows](https://github.com/gmazza/tightblog/blob/51a9768a5ab867bd176d33c0172d9b0262dd9fea/app/src/main/webapp/WEB-INF/jsps/admin/Planets.jsp#L65), which partially works but the unwanted <divs> wrapping the <trs> end up causing the table-level styling (column widths, in my case) to be ignored -- no matter where I place the width percentages -- at col, th, or with the tr's being created.

**Comment by gmazza** [comment]
I switched to JsRender, which is working fine for me.

**Comment by mklement0** [comment]
**Note:** @itimryan  mentions a potential problem with this PR in a comment on issue #101:

> I found your code brought about a new bug, when I use your option 
> noDivWrapper: true
> 
> Then the prepend option will be no longer has any effect
> prepend: true
> 
> All elements are just appended to the container.
> And after I removed 
> noDivWrapper: true
> The prepend option comes back again.

**Comment by codepb** [comment]
This has now been resolved so there is never a div wrapper. Closing as will not merge this as a result.

**Pull request closed without merging**
